# Workflow name
name: "Storybook Chromatic Deployment"

# Event for the workflow
on:
  pull_request:
    paths:
      - "src/**/*.stories.tsx"
      - "src/**/*.stories.ts"
      - "src/stories/**"
      - ".storybook/**"
      - "src/styles/**"
      - "tokens/**"
  push:
    branches:
      - main
    paths:
      - "src/**/*.stories.tsx"
      - "src/**/*.stories.ts"
      - "src/stories/**"
      - ".storybook/**"
      - "src/styles/**"
      - "tokens/**"

# List of jobs
jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
        #ðŸ‘‡ Adds Chromatic as a step in the workflow
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #ðŸ‘‡ Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
